//created on: 06-may-2017
package reglas
import control.Message

rule "buenos dias"
    when
        m : Message( message == "buenos dias", myMessage : message )
    then
        m.setStatus( "Saludo" );
        update( m );
end


rule "hola"
    when
        m : Message( message == "hola", myMessage : message )
    then
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( "Saludo" );
        update( m );
end


rule "GoodBye"
    when
        Message( message == "hola", myMessage : message )
    then
        System.out.println( myMessage );
end
