//created on: 06-may-2017
package reglas
import model.Message
import model.TypeMessage
import model.Enumerations.EtypeMessage
import utiles.KeyWords


rule "Saludo"

   
    when
        m : Message( utiles.KeyWords.saludo contains message  , myMessage : message )
    then
       
       TypeMessage  type =new TypeMessage();
       type.setTypeMessage("Saludo");
       type.setIdTypeMessage(EtypeMessage.SALUDO.ordinal()); 
        m.setTypeMessage(type);
        
end


rule "Despedida"

   
    when
        m : Message( utiles.KeyWords.despedida contains message  , myMessage : message )
    then
       
       TypeMessage  type =new TypeMessage();
       type.setTypeMessage("Despedida");
       type.setIdTypeMessage(EtypeMessage.DESPEDIDA.ordinal()); 
        m.setTypeMessage(type);
        
end

rule "Deporte"

   
    when
        m : Message( utiles.KeyWords.deporte contains message  , myMessage : message )
    then
       
       TypeMessage  type =new TypeMessage();
       type.setTypeMessage("Deporte");
       type.setIdTypeMessage(EtypeMessage.DEPORTE.ordinal()); 
        m.setTypeMessage(type);
        
end
rule "Familia"

   
    when
        m : Message( utiles.KeyWords.familia contains message  , myMessage : message )
    then
       
       TypeMessage  type =new TypeMessage();
       type.setTypeMessage("Familia");
       type.setIdTypeMessage(EtypeMessage.FAMILIA.ordinal()); 
        m.setTypeMessage(type);
        
end

rule "Tiempo"

   
    when
        m : Message( utiles.KeyWords.tiempo contains message  , myMessage : message )
    then
       
       TypeMessage  type =new TypeMessage();
       type.setTypeMessage("Tiempo");
       type.setIdTypeMessage(EtypeMessage.TIEMPO.ordinal()); 
        m.setTypeMessage(type);
        
end

rule "Trabajo"

   
    when
        m : Message( utiles.KeyWords.trabajo contains message  , myMessage : message )
    then
       
       TypeMessage  type =new TypeMessage();
       type.setTypeMessage("Trabajo");
       type.setIdTypeMessage(EtypeMessage.TRABAJO.ordinal()); 
        m.setTypeMessage(type);
        
end


rule "Gusto"

    when
        m : Message( utiles.KeyWords.gustos contains message  , myMessage : message )
    then
       
       TypeMessage  type =new TypeMessage();
       type.setTypeMessage("Gusto");
        m.setTypeMessage(type);
        
end
