//created on: 06-may-2017
package reglas
import control.Message

rule "GOOD MORNING"
    when
        m : Message( message == "GOOD MORNING", myMessage : message )
    then
        m.setTypeMessage( "Saludo" );
        update( m );
end


rule "HELLO"
    when
        m : Message( message == "HELLO", myMessage : message )
    then
        m.setTypeMessage( "Saludo" );
        update( m );
end


rule "HI"
    when
        Message( message == "HI", myMessage : message )
    then
        System.out.println( myMessage );
end
