-- MySQL Script generated by MySQL Workbench
-- Thu May 11 01:54:00 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema musicdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema musicdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `musicdb` DEFAULT CHARACTER SET utf8 ;
USE `musicdb` ;

-- -----------------------------------------------------
-- Table `musicdb`.`type_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicdb`.`type_message` (
  `IdTypeMessage` INT(11) NOT NULL AUTO_INCREMENT,
  `TypeMessage` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTypeMessage`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musicdb`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicdb`.`messages` (
  `IdMessage` INT(11) NOT NULL AUTO_INCREMENT,
  `Message` TEXT NOT NULL,
  `IdTypeMessage` INT(11) NOT NULL,
  PRIMARY KEY (`IdMessage`),
  INDEX `IdTypeMessage_idx` (`IdTypeMessage` ASC),
  CONSTRAINT `IdTypeMessage`
    FOREIGN KEY (`IdTypeMessage`)
    REFERENCES `musicdb`.`type_message` (`IdTypeMessage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musicdb`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicdb`.`states` (
  `idState` INT(11) NOT NULL AUTO_INCREMENT,
  `State` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idState`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musicdb`.`musics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicdb`.`musics` (
  `IdMusic` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(250) NOT NULL,
  `URL` VARCHAR(250) NOT NULL,
  `IdState` INT(11) NOT NULL,
  PRIMARY KEY (`IdMusic`),
  INDEX `IdState_idx` (`IdState` ASC),
  CONSTRAINT `IdState`
    FOREIGN KEY (`IdState`)
    REFERENCES `musicdb`.`states` (`idState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musicdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicdb`.`users` (
  `IdUser` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(1024) NOT NULL,
  `Login` VARCHAR(256) NOT NULL,
  `LastName` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`IdUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musicdb`.`user_music`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicdb`.`user_music` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Correct` BIT(1) NOT NULL,
  `IdUser` INT(11) NOT NULL,
  `IdMusic` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IdUser_idx` (`IdUser` ASC),
  INDEX `IdMusic_idx` (`IdMusic` ASC),
  CONSTRAINT `IdMusic`
    FOREIGN KEY (`IdMusic`)
    REFERENCES `musicdb`.`musics` (`IdMusic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdUser`
    FOREIGN KEY (`IdUser`)
    REFERENCES `musicdb`.`users` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
